
# DO NOT DELETE

Gauss_main.o: util.h Gauss_solve.h
Gauss_solve.o: Gauss_solve.h util.h
Gauss_test.o: /usr/include/gtest/gtest.h
Gauss_test.o: /usr/include/gtest/gtest-assertion-result.h
Gauss_test.o: /usr/include/gtest/gtest-message.h
Gauss_test.o: /usr/include/gtest/internal/gtest-port.h /usr/include/ctype.h
Gauss_test.o: /usr/include/features.h /usr/include/features-time64.h
Gauss_test.o: /usr/include/stdc-predef.h /usr/include/stdio.h
Gauss_test.o: /usr/include/stdlib.h /usr/include/alloca.h
Gauss_test.o: /usr/include/string.h /usr/include/strings.h
Gauss_test.o: /usr/include/gtest/internal/custom/gtest-port.h
Gauss_test.o: /usr/include/gtest/internal/gtest-port-arch.h
Gauss_test.o: /usr/include/unistd.h /usr/include/regex.h
Gauss_test.o: /usr/include/gtest/gtest-death-test.h
Gauss_test.o: /usr/include/gtest/internal/gtest-death-test-internal.h
Gauss_test.o: /usr/include/gtest/gtest-matchers.h
Gauss_test.o: /usr/include/gtest/gtest-printers.h
Gauss_test.o: /usr/include/gtest/internal/gtest-internal.h
Gauss_test.o: /usr/include/gtest/internal/gtest-filepath.h
Gauss_test.o: /usr/include/gtest/internal/gtest-string.h
Gauss_test.o: /usr/include/gtest/internal/gtest-type-util.h
Gauss_test.o: /usr/include/gtest/internal/custom/gtest-printers.h
Gauss_test.o: /usr/include/gtest/gtest-param-test.h
Gauss_test.o: /usr/include/gtest/internal/gtest-param-util.h
Gauss_test.o: /usr/include/gtest/gtest-test-part.h
Gauss_test.o: /usr/include/gtest/gtest-typed-test.h
Gauss_test.o: /usr/include/gtest/gtest_pred_impl.h
Gauss_test.o: /usr/include/gtest/gtest_prod.h Gauss_solve.h util.h
util.o: util.h
