name: "Lint & Style Check"

on: [pull_request, push]

jobs:
  check-formatting:
    runs-on: ubuntu-24.04


    strategy:
      fail-fast: false
      matrix:
        task:
        - 00.DummyMake
        - 01.InplaceSorting
        - 02.Base85
        - 03.Gauss

    steps:

    - name: Получение кода и actions
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Инсталляция инструментов
      uses: ./.github/actions/install-prerequisites

    - name: Стиль кодирования
      uses: per1234/artistic-style-action@v1
      with:
        options-file-path: 'astyle.ini'
        target-paths: "- ./${{ matrix.task }}/"
        name-patterns: |
          - '*.cpp'
          - '*.h'

    - name: Статический анализ clang-tidy
      run: |
        pushd "${{ matrix.task }}"
        make tidy
        popd
